package io.github.edadma.wasm.spec

import java.nio.file.{Files, Path, Paths}
import scala.jdk.CollectionConverters.*

/** JVM-only entry point for the W3C spec test runner.
  *
  * The manifests live under `interp/jvm/src/test/resources/spec/` and
  * are regenerated by `scripts/build-spec-tests.sh` from a local
  * checkout of github.com/WebAssembly/testsuite. This main class walks
  * every `<name>.json` in that directory and invokes [[SpecRunner]] on
  * each one, then prints a per-file summary plus a final pass/fail
  * counter.
  *
  *   sbt 'interpJVM/Test/runMain io.github.edadma.wasm.spec.SpecComplianceTests'
  *
  * Exits non-zero if any file is not green. A `.wast` file that we
  * know fails (e.g. due to a missing proposal) goes into
  * [[KnownFailures.expectedFailures]] with a note — the runner still
  * runs it but the overall sweep stays green so the rest of the
  * coverage isn't masked.
  */
object SpecComplianceTests:

  def main(args: Array[String]): Unit =
    println()
    println("== W3C spec compliance ==")

    val dir = locateResourceDir().getOrElse {
      println("  spec resource dir not found — run scripts/build-spec-tests.sh first")
      println()
      sys.exit(0)
    }

    val manifests = Files.list(dir).iterator.asScala
      .filter(p => p.getFileName.toString.endsWith(".json"))
      .toVector
      .sortBy(_.getFileName.toString)

    if manifests.isEmpty then
      println(s"  no manifests under $dir — run scripts/build-spec-tests.sh first")
      println()
      sys.exit(0)

    val results = manifests.map { mf =>
      val stats = new SpecRunner(mf).run()
      reportFile(stats)
      stats
    }

    println()
    val totPassed = results.iterator.map(_.passed).sum
    val totSkip   = results.iterator.map(_.skipped).sum
    val totFail   = results.iterator.map(_.failures.size).sum
    val grandTotal = totPassed + totSkip + totFail
    println(s"== Spec totals: $totPassed passed, $totFail failed, $totSkip skipped (of $grandTotal) ==")

    val unexpectedFailures = results.filter(s => s.failures.nonEmpty && !KnownFailures.expected(s.name))
    val unexpectedPasses   = results.filter(s => s.failures.isEmpty && KnownFailures.expected(s.name))

    if unexpectedPasses.nonEmpty then
      println()
      println("UNEXPECTED PASSES (consider removing from KnownFailures):")
      unexpectedPasses.foreach(s => println(s"  - ${s.name}"))

    if unexpectedFailures.nonEmpty then
      println()
      println(s"FAILED: ${unexpectedFailures.size} manifest(s) reported failures not on the known list:")
      unexpectedFailures.foreach { s =>
        println(s"  - ${s.name}")
        s.failures.take(5).foreach { case (line, msg) => println(s"      line $line: $msg") }
        if s.failures.size > 5 then println(s"      ... and ${s.failures.size - 5} more")
      }
      sys.exit(1)

    println()

  private def reportFile(stats: SpecRunner.Stats): Unit =
    val tag =
      if stats.failures.isEmpty then "OK   "
      else if KnownFailures.expected(stats.name) then "KNOWN"
      else "FAIL "
    println(f"  $tag%-5s ${stats.name}%-22s ${stats.passed}%5d pass, ${stats.failures.size}%4d fail, ${stats.skipped}%4d skip")

  /** Walk upward from CWD looking for the resource directory, since
    * `sbt 'interpJVM/Test/runMain'` may set CWD to either the project
    * root or the JVM subproject depending on the sbt version. */
  private def locateResourceDir(): Option[Path] =
    val rel = "interp/jvm/src/test/resources/spec"
    val cwd = Paths.get("").toAbsolutePath
    LazyList.iterate[Option[Path]](Some(cwd))(_.flatMap(p => Option(p.getParent)))
      .take(6)
      .flatten
      .map(_.resolve(rel))
      .find(Files.isDirectory(_))

/** Manifests we know currently report failures and the gap they
  * represent.
  *
  * Marking one here keeps the overall sweep green so the rest of the
  * coverage isn't masked, but the FAIL count still prints so the gap
  * stays visible. Each entry is a separate follow-up TODO — when the
  * underlying gap is fixed, remove the name and the runner will then
  * complain about it as an "UNEXPECTED PASS" until the entry is
  * cleared.
  */
private[spec] object KnownFailures:

  /** Manifest names (sans `.json` extension) expected to have failures.
    *
    * Grouped by the feature gap each represents — all of these need
    * non-trivial implementation work beyond the surgical bug-fix
    * pattern. Pinning here keeps the sweep green while the gaps stay
    * visible. See `docs/content/reference/spec-compliance.md` for the
    * follow-up tracking table.
    *
    * --- Function-references / GC proposals (not on the roadmap) ---
    *   - `br_table`      — module 0 uses `(ref null func)` short form (0x63)
    *   - `table-sub`     — same reftype short form
    *   - `local_init`    — `(ref func)` non-null short form (0x64)
    *   - `unreached-valid` — function-references + typed reftype lookup
    *
    * --- Imported globals (gates 7 manifests) ---
    * Parser doesn't yet handle the import kind 0x03 (global) form, so
    * the globaltype bytes (valtype + mut) are misread as a new import.
    *   - `data`, `elem`, `exports`, `global`, `imports`, `names`,
    *     `memory_grow`, `table_copy`, `table_grow`
    *
    * --- Cross-module `register` (runner-side) ---
    * The wast2json command stream includes `register` commands that bind
    * a module instance to an external name for subsequent imports; our
    * runner doesn't implement that dispatch yet.
    *   - `linking`
    *
    */
  private val names: Set[String] = Set(
    // Function-references / GC proposals
    "br_table",
    "table-sub",
    "local_init",
    "unreached-valid",
    // Imported globals
    "data",
    "elem",
    "exports",
    "global",
    "imports",
    "names",
    "memory_grow",
    "table_copy",
    "table_grow",
    // Cross-module register
    "linking",
  )

  def expected(name: String): Boolean = names.contains(name)
